using SPGenerator.Generator.Database.Model;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SPGenerator.Generator.Database
{
    public class GeneratorDbInitializer : DropCreateDatabaseIfModelChanges<GeneratorDbContext>
    {
        protected override void Seed(GeneratorDbContext context)
        {
            initTexts(context);
            base.Seed(context);
        }

        private static void initTexts(GeneratorDbContext context)
        {
            context.Texts.Add(new Text() { Content = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris commodo in quam eget viverra. Etiam molestie luctus leo tincidunt dapibus. Etiam in imperdiet diam. Nunc ac orci at sapien posuere dignissim. Praesent aliquam sapien vel diam pulvinar eleifend. Curabitur placerat risus vitae magna tempor rutrum. Duis varius felis sed pretium eleifend. Mauris luctus risus ut tortor lobortis hendrerit. Nunc luctus laoreet tincidunt. Morbi nec tortor eget eros convallis cursus ac at elit. Ut vitae pulvinar neque. Ut sit amet suscipit tortor. Quisque sapien ligula, euismod sit amet tempor id, sagittis sit amet magna. Quisque accumsan gravida massa eget ultrices. Aliquam sodales lorem at libero vestibulum consectetur eu sit amet lectus. Praesent sagittis, sem ut pretium ultricies, risus nisl sollicitudin lorem, non vehicula nulla odio a diam. Cras tincidunt efficitur tortor. Curabitur egestas vehicula venenatis. Vivamus vel mauris pulvinar felis mattis varius. Suspendisse vitae neque turpis. Nam faucibus, lacus nec bibendum convallis, libero eros maximus augue, vel consectetur est arcu at risus. Pellentesque sed quam eu eros condimentum lacinia. Phasellus tellus nibh, tincidunt ac sapien ut, condimentum consequat arcu. Donec non viverra nulla. In tincidunt, lacus sit amet lacinia aliquet, augue diam iaculis velit, sit amet ultrices leo velit a metus. Quisque eget vehicula dui. Vivamus dignissim justo sed finibus luctus." });
            context.Texts.Add(new Text() { Content = @"Aliquam sodales lorem at libero vestibulum consectetur eu sit amet lectus. Praesent sagittis, sem ut pretium ultricies, risus nisl sollicitudin lorem, non vehicula nulla odio a diam. Cras tincidunt efficitur tortor. Curabitur egestas vehicula venenatis. Vivamus vel mauris pulvinar felis mattis varius. Suspendisse vitae neque turpis. Nam faucibus, lacus nec bibendum convallis, libero eros maximus augue, vel consectetur est arcu at risus. Pellentesque sed quam eu eros condimentum lacinia. Phasellus tellus nibh, tincidunt ac sapien ut, condimentum consequat arcu. Donec non viverra nulla. In tincidunt, lacus sit amet lacinia aliquet, augue diam iaculis velit, sit amet ultrices leo velit a metus. Quisque eget vehicula dui. Vivamus dignissim justo sed finibus luctus. Nam fermentum augue consequat purus sollicitudin, eu imperdiet nisi porttitor. In pharetra non eros vel suscipit. Suspendisse ac ante sit amet ipsum auctor congue. Nunc efficitur, tortor ac vestibulum posuere, eros arcu tincidunt diam, eu mattis lectus nulla et risus. Morbi et sem vel diam consectetur gravida id quis ipsum. Nunc sed tempus lorem, id porta metus. Suspendisse scelerisque fringilla tortor, non consectetur augue imperdiet ornare. Vivamus dapibus leo lectus, convallis hendrerit velit accumsan nec. Ut ut augue cursus, feugiat turpis eu, porttitor ligula." });
            context.Texts.Add(new Text() { Content = @"Nam fermentum augue consequat purus sollicitudin, eu imperdiet nisi porttitor. In pharetra non eros vel suscipit. Suspendisse ac ante sit amet ipsum auctor congue. Nunc efficitur, tortor ac vestibulum posuere, eros arcu tincidunt diam, eu mattis lectus nulla et risus. Morbi et sem vel diam consectetur gravida id quis ipsum. Nunc sed tempus lorem, id porta metus. Suspendisse scelerisque fringilla tortor, non consectetur augue imperdiet ornare. Vivamus dapibus leo lectus, convallis hendrerit velit accumsan nec. Ut ut augue cursus, feugiat turpis eu, porttitor ligula. Donec at auctor magna. Integer ex erat, luctus id augue vitae, venenatis euismod dui. Aenean ut mattis metus, in venenatis nisl. Duis a molestie ante. Aliquam vel consectetur nisl. Curabitur scelerisque, nisi quis laoreet vulputate, dui lectus congue augue, quis lobortis odio tellus ac urna. Aenean luctus porta lorem sit amet vulputate. Donec sapien arcu, fermentum sed justo vitae, tincidunt consectetur diam. Integer ultrices quis sapien non tempor. Duis a elementum eros, et imperdiet enim. In quis sem vitae tellus aliquam luctus. Aenean auctor facilisis cursus." });
            context.Texts.Add(new Text() { Content = @"Donec at auctor magna. Integer ex erat, luctus id augue vitae, venenatis euismod dui. Aenean ut mattis metus, in venenatis nisl. Duis a molestie ante. Aliquam vel consectetur nisl. Curabitur scelerisque, nisi quis laoreet vulputate, dui lectus congue augue, quis lobortis odio tellus ac urna. Aenean luctus porta lorem sit amet vulputate. Donec sapien arcu, fermentum sed justo vitae, tincidunt consectetur diam. Integer ultrices quis sapien non tempor. Duis a elementum eros, et imperdiet enim. In quis sem vitae tellus aliquam luctus. Aenean auctor facilisis cursus. Sed ac posuere ipsum. Praesent et risus porttitor, sollicitudin lectus eget, lacinia tortor. Duis eget tincidunt massa, non molestie quam. Nulla massa erat, commodo nec nibh at, sagittis venenatis eros. Quisque auctor leo dui, nec suscipit sem dapibus in. In sem turpis, posuere in elementum sed, lobortis ac mi. In sapien ipsum, consectetur quis enim eget, elementum luctus est. Maecenas eu mauris id nunc tincidunt faucibus." });
            context.Texts.Add(new Text() { Content = @"Sed ac posuere ipsum. Praesent et risus porttitor, sollicitudin lectus eget, lacinia tortor. Duis eget tincidunt massa, non molestie quam. Nulla massa erat, commodo nec nibh at, sagittis venenatis eros. Quisque auctor leo dui, nec suscipit sem dapibus in. In sem turpis, posuere in elementum sed, lobortis ac mi. In sapien ipsum, consectetur quis enim eget, elementum luctus est. Maecenas eu mauris id nunc tincidunt faucibus. Sed finibus, ligula id suscipit porttitor, risus turpis lobortis lectus, ac placerat dui tortor quis neque. Duis malesuada nunc ullamcorper molestie interdum. Mauris accumsan posuere luctus. Nunc ut magna felis. Phasellus tincidunt cursus ligula, a ultricies justo viverra eget. Morbi tempor non metus nec mattis. Sed id vulputate arcu. Pellentesque dictum tristique velit, nec auctor ligula venenatis ut. Aliquam hendrerit metus sed sodales facilisis. Phasellus at aliquet tellus, vitae suscipit mi. Vivamus cursus libero et placerat dapibus. Nunc dapibus finibus ex, sit amet accumsan orci luctus et. Nullam at mi facilisis, tempor erat luctus, consequat diam. Pellentesque feugiat lorem lectus, a maximus ante accumsan sed. Maecenas scelerisque lectus at ante tristique aliquam." });
            context.Texts.Add(new Text() { Content = @"In hendrerit metus sed sodales facilisis. Phasellus at aliquet tellus, vitae suscipit mi. Vivamus cursus libero et placerat dapibus. Nunc dapibus finibus ex, sit amet accumsan orci luctus et. Nullam at mi facilisis, tempor erat luctus, consequat diam. Pellentesque feugiat lorem lectus, a maximus ante accumsan sed. Maecenas scelerisque lectus at ante tristique aliquam. Suspendisse potenti. Maecenas mauris ante, interdum nec pulvinar vel, pellentesque eu diam. In gravida sem a euismod sollicitudin. Etiam eleifend ipsum ac volutpat viverra. Ut lobortis neque et sagittis condimentum. Nunc lacus augue, tincidunt imperdiet ex vitae, maximus rutrum quam. Aliquam ligula magna, luctus at finibus ac, facilisis non purus. Sed ac odio ut elit varius accumsan. Proin quis risus vulputate, porta ex at, suscipit velit. Phasellus imperdiet diam et tempus porttitor. Praesent bibendum felis ac fermentum vehicula. Duis eget libero at velit varius pharetra. Nullam ultricies ut massa vel mollis. Cras nisl elit, vulputate nec tempor a, pharetra vulputate ex. Donec dignissim blandit fermentum. Nulla facilisi." });
            context.Texts.Add(new Text() { Content = @"Suspendisse potenti. Maecenas mauris ante, interdum nec pulvinar vel, pellentesque eu diam. In gravida sem a euismod sollicitudin. Etiam eleifend ipsum ac volutpat viverra. Ut lobortis neque et sagittis condimentum. Nunc lacus augue, tincidunt imperdiet ex vitae, maximus rutrum quam. Aliquam ligula magna, luctus at finibus ac, facilisis non purus. Sed ac odio ut elit varius accumsan. Proin quis risus vulputate, porta ex at, suscipit velit. Phasellus imperdiet diam et tempus porttitor. Praesent bibendum felis ac fermentum vehicula. Duis eget libero at velit varius pharetra. Nullam ultricies ut massa vel mollis. Cras nisl elit, vulputate nec tempor a, pharetra vulputate ex. Donec dignissim blandit fermentum. Nulla facilisi. Curabitur vel finibus nisl, nec tincidunt mauris. Ut sit amet sem ac urna volutpat bibendum. Pellentesque lacus metus, porta vitae maximus ac, semper non ex. Nunc eget mauris vitae leo porta vestibulum vel eget magna. Phasellus fringilla fermentum dui sit amet blandit. Phasellus at faucibus magna. Praesent congue volutpat lorem, ac vehicula metus ornare vel. Fusce non quam a turpis feugiat elementum sit amet quis neque. Curabitur vitae dolor fermentum, cursus ex quis, rutrum lorem. Maecenas fermentum facilisis ante molestie dictum. Phasellus et malesuada justo. Nunc non dolor a dolor tempor laoreet. Donec rutrum risus velit, convallis tincidunt ex ornare at. Nam nec aliquet neque, vel porta diam. Aenean dolor nisl, luctus sed hendrerit id, rhoncus eget dui. Etiam vehicula massa non lorem rhoncus, non efficitur diam fringilla." });
            context.Texts.Add(new Text() { Content = @"Curabitur vel finibus nisl, nec tincidunt mauris. Ut sit amet sem ac urna volutpat bibendum. Pellentesque lacus metus, porta vitae maximus ac, semper non ex. Nunc eget mauris vitae leo porta vestibulum vel eget magna. Phasellus fringilla fermentum dui sit amet blandit. Phasellus at faucibus magna. Praesent congue volutpat lorem, ac vehicula metus ornare vel. Fusce non quam a turpis feugiat elementum sit amet quis neque. Curabitur vitae dolor fermentum, cursus ex quis, rutrum lorem. Maecenas fermentum facilisis ante molestie dictum. Phasellus et malesuada justo. Nunc non dolor a dolor tempor laoreet. Donec rutrum risus velit, convallis tincidunt ex ornare at. Nam nec aliquet neque, vel porta diam. Aenean dolor nisl, luctus sed hendrerit id, rhoncus eget dui. Etiam vehicula massa non lorem rhoncus, non efficitur diam fringilla. Mauris suscipit faucibus rutrum. Morbi condimentum dui eros, in imperdiet diam tristique eget. Nunc eu vehicula urna. Proin dignissim, nisi sed viverra fringilla, erat tellus accumsan est, ut viverra libero erat ac quam. Nam tincidunt, massa vel facilisis ultrices, lorem mi suscipit orci, ut mattis dui neque et justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas sit amet rutrum augue, et consectetur nisl. Proin quis ullamcorper quam, a volutpat erat." });
        }
    }
}
